name: 'Action Set Assignees'
description: 'Set assignees to an issue or a pull request'
author: 'Incode Technologies, Inc.'

inputs:
  github_token:
    description: 'A GitHub token.'
    required: true
  assignee:
    description: 'The assignee to be set.'
    default: ${{ github.actor }}
  repo:
    description: 'The owner and repository name.'
    required: false
    default: ${{ github.repository }}

runs:
  using: node20
  main: dist/index.js
